# Copyright (c) 2026, School Management and contributors
# For license information, please see license.txt

import frappe

def execute(filters=None):
    """Certificate Issuance Report - Track certificates generated"""
    columns = [
        {"label": "Student", "fieldname": "student", "fieldtype": "Link", "options": "Custom Student", "width": 120},
        {"label": "Student Name", "fieldname": "student_name", "fieldtype": "Data", "width": 150},
        {"label": "Certificate Type", "fieldname": "template", "fieldtype": "Data", "width": 150},
        {"label": "Generated On", "fieldname": "generated_on", "fieldtype": "Datetime", "width": 140},
        {"label": "Generated By", "fieldname": "generated_by", "fieldtype": "Data", "width": 120},
        {"label": "Status", "fieldname": "status", "fieldtype": "Data", "width": 80}
    ]
    conditions = "1=1"
    if filters:
        if filters.get("from_date"):
            conditions += " AND sc.generated_on >= '{0}'".format(filters["from_date"])
        if filters.get("to_date"):
            conditions += " AND sc.generated_on <= '{0}'".format(filters["to_date"])
        if filters.get("template"):
            conditions += " AND sc.template = '{0}'".format(filters["template"])
    data = frappe.db.sql("""
        SELECT sc.student, sc.student_name, sc.template,
               sc.generated_on, sc.generated_by, sc.status
        FROM `tabStudent Certificate` sc
        WHERE {0}
        ORDER BY sc.generated_on DESC
    """.format(conditions), as_dict=True)
    return columns, data
