# Copyright (c) 2026, School Management and contributors
# For license information, please see license.txt

import frappe
from frappe import _

def execute(filters=None):
    columns = get_columns()
    data = get_data(filters)
    return columns, data

def get_columns():
    return [
        _("Certificate ID") + ":Link/Student Certificate:180",
        _("Student Name") + "::200",
        _("Certificate Type") + "::200",
        _("Template") + ":Link/Certificate Template:180",
        _("Issue Date") + ":Date:120",
        _("Generated By") + ":Link/User:180",
        _("Status") + "::120",
        _("Purpose") + "::200"
    ]

def get_data(filters):
    conditions = get_conditions(filters)
    query = """
        SELECT
            sc.name,
            sc.student_name,
            sc.certificate_pdf,
            sc.template,
            sc.generated_on,
            sc.generated_by,
            sc.status,
            sc.remarks
        FROM
            `tabStudent Certificate` sc
        WHERE
            sc.docstatus < 2
            {conditions}
        ORDER BY
            sc.generated_on DESC
    """.format(conditions=conditions)
    return frappe.db.sql(query, filters, as_dict=1)

def get_conditions(filters):
    conditions = []
    if filters:
        if filters.get("from_date"):
            conditions.append("AND sc.generated_on >= %(from_date)s")
        if filters.get("to_date"):
            conditions.append("AND sc.generated_on <= %(to_date)s")
        if filters.get("status"):
            conditions.append("AND sc.status = %(status)s")
        if filters.get("template"):
            conditions.append("AND sc.template = %(template)s")
    return " " . join(conditions)
