# School Management - Frappe App
# Auto-generated from Excel customization exports for ERPNext v15 Education module

app_name = "school_management_software"
app_title = "School Management"
app_publisher = "School Management"
app_description = "School Management Software - Custom ERPNext Education Module with Admissions, Hostel, Library, Transport, Events, Exams, and more"
app_email = "admin@schoolmanagement.com"
app_license = "MIT"

# Server script names - fixtures for this app (extracted from actual fixture files)
server_script_names = [
    "Auto Create Alumni Record on Student Exit",
    "Biometric Attendance Sync",
    "approved",
    "auto-calculate everything",
    "auto-create Hostel Admission on Approve",
    "auto-create Sales Invoice on submit",
    "auto-generate Gate Pass Number on approval",
    "auto-populate document rows on new form",
    "block duplicate applications",
    "Book Issue - Mark Copy as Issued",
    "Book Issue - Validate & Set Due Date",
    "Book Return - Release Book Copy",
    "Complaint assigned and to notify maintenance",
    "create_fine_on_book_return",
    "fee auto calculation",
    "frees the room if the student check-out",
    "generate_course_schedule",
    "generate_employee_certificate",
    "generate_student_certificate",
    "generate_student_id_cards",
    "get_instructor_weekly_timetable",
    "handle the actual check-in transition",
    "hostel_card_action",
    "Library Fine - Process Payment",
    "Notification Script",
    "Prevent Duplicate Active Assignments",
    "Prevent Duplicate Certificates",
    "Scheduler Event Frequency Daily",
    "Student event Celebration",
    "sync data when enrollment is submitted",
    "the actual generation logic",
    "to keep room_display updated automatically",
    "to update room occupancy",
    "Validate Hall Capacity",
]

# Client script names - fixtures for this app (extracted from actual fixture files)
client_script_names = [
    "add botton at student id card batch",
    "Approve/Reject buttons",
    "Approve/Reject buttons on Hostel Application",
    "auto fetch book copy details",
    "Auto Fetch Employee Details",
    "Auto fetch room details",
    "auto fetch student and student group",
    "Auto fetch student details to id card",
    "Auto fetch student details to leave",
    "auto fetch student room details",
    "auto fetch student transport assignment",
    "auto fill student detila into libraty member",
    "auto-fetch fee data when Student Admission is selected",
    "auto-fetch on room select",
    "auto-fetch on student",
    "auto-fetch Room/Block/Warden on student select + live duration",
    "Auto-fetch Route Details",
    "Auto-fill Generated On & Generated By",
    "auto-fill student_name",
    "automatically fetch all student details",
    "Auto-set Assigned Date",
    "Book Issue",
    "book return",
    "button on Hostel form to trigger",
    "Check-In button + Print Slip button",
    "date validation for school events",
    "Default Status",
    "filter dropdown to only show allocatable rooms + render the live card",
    "Generate Hostel Fee button",
    "hide columns from Student role",
    "hostel card creation",
    "Hostel fee automation",
    "Kit status Color",
    "Library Member Overview",
    "Mark Check-Out button",
    "Occupancy History button",
    "quick view button guardian profile",
    "quick view button on custom student list",
    "shows only Student templates.",
    "Student Kit issue",
    "student kit view",
    "Student progress card creation",
    "teacher time table  schedule",
    "time table preview",
    "to_render mess summary",
    "to show Fee Structure components and documents",
    "update Status to Submitted",
    "Validate Max Book Issue Limit",
    "View Attendance button",
    "Wardens Complaints",
]

# Fixtures for customizations - these auto-install on app migration
fixtures = [
    # Custom Server Scripts (listed by name to avoid conflicts with other apps)
    {"dt": "Server Script", "filters": [
        ["name", "in", server_script_names]
    ]},

    # Custom Client Scripts (listed by name to avoid conflicts with other apps)
    {"dt": "Client Script", "filters": [
        ["name", "in", client_script_names]
    ]},

    # Custom Workspaces
    {"dt": "Workspace", "filters": [["name", "in", [
        "Admissions",
        "Attendance & Assessments",
        "Exam",
        "Home",
        "Hostel-Management",
        "Library",
        "Masters",
        "Overview",
        "School Events",
        "Student Fees",
        "Student & Scheduling",
        "Transport"
    ]]}
]

# No after_migrate needed - all customizations are auto-discovered
# DocTypes are loaded from doctype/name/name.json
# Reports are loaded from report/name/name.json
# Print Formats are loaded from print_format/name/name.json
# Server Scripts, Client Scripts, and Workspaces are loaded from fixtures/
after_migrate = []
